"""
Detection Alert Dispatcher for Non-Intrusive Telemetry Analysis.

Formats, logs, and dispatches high-confidence security alerts generated by ML
models or Falco behavioral rules into DuckDB/SQLite databases, audit log streams,
and real-time SOC analyst dashboards.
"""

import json
import logging
import time
from pathlib import Path
from typing import Dict, Any, Optional

from ml_engine.config import AUDIT_LOG_PATH, SEVERITY_LEVELS

logger = logging.getLogger("ml_engine.alert_dispatcher")

class AlertDispatcher:
    """
    Handles security alerts produced by behavioral rules or ML ensemble models.
    """

    def __init__(self, db_manager=None):
        self.db_manager = db_manager
        self.audit_log_path = Path(AUDIT_LOG_PATH)
        self.audit_log_path.parent.mkdir(parents=True, exist_ok=True)

    def dispatch_alert(
        self,
        event: Dict[str, Any],
        threat_type: str,
        confidence: float,
        detection_source: str,
        rule_info: Optional[Dict[str, Any]] = None,
        ml_scores: Optional[Dict[str, float]] = None
    ) -> Dict[str, Any]:
        """
        Constructs and records a security threat detection alert.
        """
        severity = SEVERITY_LEVELS.get(threat_type, "HIGH")
        if rule_info and "severity" in rule_info:
            severity = rule_info["severity"]

        alert = {
            "timestamp": time.time(),
            "alert_id": f"ALT-{int(time.time() * 1000)}-{event.get('pid', 0)}",
            "threat_type": threat_type,
            "threat_name": threat_type,
            "severity": severity,
            "confidence": round(confidence, 4),
            "detection_source": detection_source, # "behavioral_rule", "ensemble_ml", "isolation_forest"
            "pid": event.get("pid", 0),
            "ppid": event.get("ppid", 0),
            "comm": event.get("comm", ""),
            "exe_path": event.get("exe_path", ""),
            "cmdline": event.get("cmdline", ""),
            "container_id": event.get("container_id", ""),
            "src_ip": event.get("src_ip", ""),
            "dst_ip": event.get("dst_ip", ""),
            "dst_port": event.get("dst_port", 0),
            "mitre_id": rule_info.get("mitre_id", "T1059") if rule_info else "T1059",
            "rule_name": rule_info.get("rule_name", "") if rule_info else "",
            "description": rule_info.get("description", f"ML ensemble identified {threat_type}") if rule_info else f"ML ensemble identified {threat_type}",
            "ml_scores": ml_scores or {},
        }

        # 1. Log alert to JSONL audit log
        self._write_audit_log(alert)

        # 2. Persist to database if db_manager is available
        if self.db_manager:
            try:
                if hasattr(self.db_manager, "sqlite"):
                    self.db_manager.sqlite.insert_alert(alert)
                elif hasattr(self.db_manager, "insert_alert"):
                    self.db_manager.insert_alert(alert)
            except Exception as e:
                logger.error(f"Failed to persist alert to database: {e}")

        logger.warning(
            f"🚨 [DETECTION ALERT] {alert['severity']} {alert['threat_type']} "
            f"(PID={alert['pid']}, Comm='{alert['comm']}', Source={alert['detection_source']}, Conf={alert['confidence']:.2f})"
        )

        return alert

    def _write_audit_log(self, alert: Dict[str, Any]):
        try:
            with open(self.audit_log_path, "a", encoding="utf-8") as f:
                f.write(json.dumps(alert) + "\n")
        except Exception as e:
            logger.error(f"Failed to write alert to audit log: {e}")
